# Dimentions, tensors and reshape

In [1]:
import numpy as np

## Scalar

In [8]:
x = np.array(42)
print(f'''Shape: {x.shape}
Dimentions: {x.ndim}''')

Shape: ()
Dimentions: 0


## Vector

In [9]:
x = np.array([42, 3, 4, 5, 6, 7, 8])
print(f'''Shape: {x.shape}
Dimentions: {x.ndim}''')

Shape: (7,)
Dimentions: 1


## Matrix

In [10]:
x = np.array([[42, 3, 4, 5, 6, 7, 8],
    [1, 2, 3, 4, 5, 6, 7]])
print(f'''Shape: {x.shape}
Dimentions: {x.ndim}''')

Shape: (2, 7)
Dimentions: 2


## Tensor

In [12]:
x = np.array([[[42, 3, 4, 5, 6, 7, 8],
    [1, 2, 3, 4, 5, 6, 7]],
    [[42, 3, 4, 5, 6, 7, 8],
    [1, 2, 3, 4, 5, 6, 7]]])
print(f'''Shape: {x.shape}
Dimentions: {x.ndim}''')

Shape: (2, 2, 7)
Dimentions: 3


## Reshape

In [15]:
x = np.array([[0,1],
    [2, 5],
    [4, 6],
    [7, 9],
    [9, 4],
    [4, 1],
    [6, 3]
    ])
x.shape

(7, 2)

In [17]:
x.reshape(14, 1)

array([[0],
       [1],
       [2],
       [5],
       [4],
       [6],
       [7],
       [9],
       [9],
       [4],
       [4],
       [1],
       [6],
       [3]])

In [18]:
x.reshape(2, 7)

array([[0, 1, 2, 5, 4, 6, 7],
       [9, 9, 4, 4, 1, 6, 3]])

## Transpose

In [19]:
np.transpose(x)

array([[0, 2, 4, 7, 9, 4, 6],
       [1, 5, 6, 9, 4, 1, 3]])

In [20]:
x.T

array([[0, 2, 4, 7, 9, 4, 6],
       [1, 5, 6, 9, 4, 1, 3]])